### ISSUE TITLE
Sensors are unavailable

### ISSUE THREAD

**Issue by karl1809** [karloskar/homeassistant-goecontroller-mqtt#5]
Thank you a lot for your work.
Installation in HA was no problem. 
In the go-e-app I  set for the controller the same settings like for the charger. The charger works well in HA.
But all sensors for the controller show unavailable. I have installed mosquitto mqtt which  work well with go-e charger mqtt integration. But I can not find any Information about the controller  in the mosquitto-mqtt-explorer.  In the Prefix I have set the Backslash. 
I tried hours to debug the system but without success.
Can you help me. What can I do?

****I found my bug!*****The IP of my MQTT-Server (IP of HA) was wrong. Every detail in the go-e-app must be correct.  Thank you a lot!

**Comment by karloskar** [comment]
Glad you sorted it! Thanks for trying it out!
