### ISSUE TITLE
No sensors available

### ISSUE THREAD

**Issue by MarkusNylund** [karloskar/homeassistant-goecontroller-mqtt#6]
Hi
thanks for the integration :)

I have the same issue as the others. 

I got the charger mqtt addon working without any hassle but this controller is not working.
I have double checked that the URL and Prefix is done in same way, tried also with and without '/' prefix.
Homeassistant is able to see and create entities based on mqtt messages.

I see the mqtt messages arriving in the mqtt explorer but this plugin does not seem to be able to parse them.
Has the protocol or structure changed? On what controller firmware version was this developed and tested?

**Comment by MarkusNylund** [comment]
Seems like integration removal and adding back and a reboot did the trick.

**Comment by karloskar** [comment]
That's great to hear you got it working!
